// Generated by CoffeeScript 1.10.0
(function() {
  var getScores;

  module.exports = this;

  getScores = function(s) {
    var j, len, line, ref, results;
    ref = s.split('\n');
    results = [];
    for (j = 0, len = ref.length; j < len; j++) {
      line = ref[j];
      if (/^.?G_DATA/.test(line)) {
        results.push(Number(line.split(/\s+/)[3]));
      }
    }
    return results;
  };

  this.eq = function(a, b) {
    var diff, i, j, len, maxDiff, ref, scoresA, scoresB, value;
    ref = [a, b].map(getScores), scoresA = ref[0], scoresB = ref[1];
    if (scoresA.length !== scoresB.length) {
      return {
        equal: false,
        message: 'Different number of scores'
      };
    }
    maxDiff = 0;
    for (i = j = 0, len = scoresA.length; j < len; i = ++j) {
      value = scoresA[i];
      diff = Math.abs(scoresA[i] - scoresB[i]);
      if (maxDiff < diff) {
        maxDiff = diff;
      }
      if (diff > 2) {
        return {
          equal: false,
          message: "Score difference > 2 (" + diff + ")"
        };
      }
    }
    return {
      equal: true,
      message: "Max diff: " + maxDiff
    };
  };

}).call(this);
